-- BitHub V2 — Derivation Duplicate Cleanup
-- Auto-generated by db_cleanup_derivations.py
-- Removing 5 accidental duplicate(s)

DELETE FROM questions WHERE question_uid = '1337d28a3e7c1206a9f8bd1a433db528b2f8ccde6fb05bb86c1a1b147cfd13ad'; -- CH24101 Q.1(a) End Semester 2023
DELETE FROM questions WHERE question_uid = '3790412238822730f1774c53aad4a8e31753f860a0b8d4a2942b3bf130d8aa2f'; -- EC24101 Q.2(b) End Semester 2022
DELETE FROM questions WHERE question_uid = '768044d37feff71b5a3352ab63335b955ddaf5762e03a8aa6c9bd31b123acf10'; -- EC24101 Q.3(a) End Semester 2022
DELETE FROM questions WHERE question_uid = 'f4c39c7fd35ad5edb4675ccab4bfd6965e01ffbe2b3b530f2adcff516940e268'; -- EC24101 Q.3(a) End Semester 2024
DELETE FROM questions WHERE question_uid = '18eb30d083f6aa82607060c36b20ea775a19869c8429ef3f3b7504cda70fca36'; -- EC24101 Q.4(b) End Semester 2024
